{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.37b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_flask-{{ version }}.tar.gz
  sha256: a9fa27c8ccded2b982eefd96b772e3ac24db8bf05269527ea910444b5e8a3563

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.37b0
    - opentelemetry-instrumentation ==0.37b0
    - opentelemetry-semantic-conventions ==0.37b0
    - opentelemetry-util-http ==0.37b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-flask 
    # - markupsafe ==2.0.1
    # - flask <3.0,>=1.0
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
